### ISSUE TITLE
委外到货单审核失败

### ISSUE THREAD

**Issue by mentianyi** [microfeel/Yonyou#4]
checkbill 错误 应该是调用 FromPuArrivalVouchToStoreRecord时出错

**Comment by mentianyi** [comment]
这个BUG是因为界面处理没有容错机制，造成将扫描码提交到了送货单里

**Comment by mentianyi** [comment]
Microsoft.Data.SqlClient.SqlException (0x80131904): 将截断字符串或二进制数据。
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at Microsoft.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.NextResult()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
ClientConnectionId:8a816ef4-a355-45c2-acde-eae1c74ce9ab
Error Number:8152,State:10,Class:16
   --- End of inner exception stack trace ---
   at MicroFeel.YonYou.EntityFrameworkCore.U8DbContext.SaveRdRecordsTran(String puarrivalOrderNo, Action`1 action) in C:\Projects\Yonyou\MicroFeel.YonYou.EntityFrameworkCore\Partial\U8DbContext.cs:line 1045
   at MicroFeel.YonYou.EntityFrameworkCore.U8DbContext.FromPuArrivalVouchToStoreRecord(String puarrivalOrderNo, String sendOrderNo) in C:\Projects\Yonyou\MicroFeel.YonYou.EntityFrameworkCore\Partial\U8DbContext.cs:line 1020
   at MicroFeel.YonYou.EntityFrameworkCore.U8Service.MicroFeel.Finance.Interfaces.IDbOperation.FromPuArrivalVouchToStoreRecord(String puarrivalOrderNo, String sendOrderNo) in C:\Projects\Yonyou\MicroFeel.YonYou.EntityFrameworkCore\U8Service.cs:line 276
   at MicroFeel.JiaQi.Store.Api.Controllers.PuarrivalController.CheckBill(ParPurchaseOrder order) in C:\Projects\JiaQi\MicroFeel.JiaQi.Api\MicroFeel.JiaQi.Store.Api\Controllers\Finance\PuarrivalController.cs:line 93 An error occurred while updating the entries. See the inner exception for details.
